version: '3.7'

services:
  db:
    image: mariadb:10.2.25
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER:?MYSQL_USER is not set or is empty}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?MYSQL_PASSWORD is not set or is empty}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is not set or is empty}
      MYSQL_DATABASE: ${MYSQL_DATABASE:?MYSQL_DATABASE is not set or is empty}
    volumes:
      - backup:/var/lib/mysql


  php:
    image: ${PHP_IMAGE:?PHP_IMAGE is not set or is empty}
    environment:
      APP_DEBUG: ${APP_DEBUG:-0}
      APP_ENV: ${APP_ENV:-prod}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      APP_SECRET: ${APP_SECRET:?APP_SECRET is not set or is empty}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN:?CORS_ALLOW_ORIGIN is not set or is empty}
      DATABASE_URL: ${DATABASE_URL:?DATABASE_URL is not set or is empty}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:?TRUSTED_HOSTS is not set or is empty}

  nginx:
    restart: always
    image: ${NGINX_IMAGE:? is not set or is empty}
    depends_on:
      - php
    ports:
      - "8000:80"

volumes:
  backup:
    name: db-backup
